version: '3.8'
services:
  database:
    image: postgres
    environment:
      POSTGRES_DB: portfolio_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: CLI123
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my-network

  backend:
    container_name: backend_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - my-network

  frontend:
    container_name: frontend_container
    build:
      context: ./src/portfolio-app
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
volumes:
  db_data:
